apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "speedtest.fullname" . }}
  labels:
    {{- include "speedtest.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "speedtest.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "speedtest.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "speedtest.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: INFLUX_ADDR
              value: "{{ .Values.influxdb.address }}"
            - name: INFLUX_PORT
              value: "{{ .Values.influxdb.port }}"
            - name: INFLUX_DB
              value: "{{ .Values.influxdb.database }}"
            - name: INFLUX_USER
              value: "{{ .Values.influxdb.username }}"
            - name: INFLUX_PASS
              value: "{{ .Values.influxdb.password }}"
            - name: INFLUX_VERIFYSSL
              value: "{{ .Values.influxdb.verify_ssl }}"
            - name: TEST_DELAY
              value: "{{ .Values.speedtest.delay }}"
            - name: TEST_SERVER
              value: "{{ .Values.speedtest.server }}"
            - name: LOG_LEVEL
              value: "{{ .Values.logging.level }}"

